config/routes.rb
Rails.application.routes.draw do
  #root 'home#index'

  resources :poderes
  resources :personagens

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personagem.rb
class Personagem < ApplicationRecord
  validates_presence_of :nome, :forca, :resistencia, :agilidade, :destreza
  has_many :poderes
end

app/models/poder.rb
class Poder < ApplicationRecord
  validates_presence_of :nome, :tipo, :personagem


  belongs_to :personagem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end


end

app/controllers/personagens_controller.rb
class PersonagensController < ApplicationController

  def index
    if params[:forca].present?
      @personagem = Personagem.where(forca:params[:forca])
      else
    @personagem = Personagem.all
  end
  end

  def new
    @personagem = Personagem.new
  end

  def create
    @personagem = Personagem.new(personagem_params)

    if @personagem.save
      redirect_to @personagem,
                  notice: "Personagem criado com sucesso"
        else
          render action: :new
        end


  end

  def personagem_params

    params.require(:personagem).permit(:nome, :forca, :resistencia, :agilidade, :destreza)
  end


  def show
    @personagem = Personagem.find(params[:id])

  end

  def edit
      @personagem = Personagem.find(params[:id])
  end

  def update
  @personagem = Personagem.find(params[:id])
      if @personagem.update(personagem_params)
          redirect_to @personagem,
          notice: 'Personagem atualizado'
      else
          render action: :edit
        end
      end


end

app/controllers/poderes_controller.rb
class PoderesController < ApplicationController
    def index
        @poder = Poder.all
    end
    def new
        @poder = Poder.new
        @personagens = Personagem.all
    end
    def show
        @poder = Poder.find(params[:id])

    end
    def create
        @poder = Poder.new(poder_params)

        if @poder.save
            redirect_to @poder, :notice => 'Poder salvo'
        else
            render :new
        end

    end

    def poder_params
        params.
            require(:poder).
            permit(:nome, :tipo, :personagem_id)
    end

    def edit
        @poder = Poder.find(params[:id])
    end

    def update
        @poder = Poder.find(params[:id])
        if @poder.update(poder_params)
            redirect_to @poder,
                notice:'Poder atualizado!!!'
        else
            render action: :edit
        end
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb


<h3> Bem vindo </h3>


<p>
  Escolha uma das ações a seguir
  <ul>
    <li> <%= link_to "Criar Personagem", new_personagem_path %> </li>
    <li><%= link_to "Visualizar Personagens", personagens_path %> </li
      </ul>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uniredentor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" >APS 2 MATHEUS LIMA / VALCIR JUNIOR</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    <%= link_to 'Inicio', root_path, class: "btn btn-outline-danger"  %>
    <%= link_to 'Ver personagens', personagens_path, class: "btn btn-outline-danger"  %>
    <%= link_to 'Novo personagem', new_personagem_path, class: "btn btn-outline-danger"  %>
    <%= link_to 'Ver poderes', poderes_path, class: "btn btn-outline-danger"  %>
    <%= link_to 'Novo poder',  new_poder_path, class: "btn btn-outline-danger"  %>

    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/personagens/_form.html.erb
<% if @personagem.errors.any? %>
  <div id="erros_explanation">
    <h2> Preencha todos os campos </h2>
    <ul>
      <% @personagem.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
      <%end%>
    </ul>
  </div>
  <%end%>

<%= form_for @personagem do |f| %>
<div class="form-group">
<p>
<%= f.label :nome %> <br />
<%= f.text_field :nome %>
</p>
<p>
<%= f.label :forca %> <br />
<%= f.text_field :forca %>
</p>
<p>
<%= f.label :resistencia %> <br />
<%= f.text_field :resistencia %>
</p>
<p>
<%= f.label :agilidade %> <br />
<%= f.text_field :agilidade %>
</p>
<p>
<%= f.label :destreza %> <br />
<%= f.text_field :destreza %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/personagens/edit.html.erb
<h1> Editar Perfil </h1>

<%= render 'form' %>

<%= link_to "Voltar", @personagem %>

app/views/personagens/index.html.erb
<%= form_tag("/personagens", method: "get") do %>
  <b>Força: </b>
  <%= number_field_tag(:forca, params[:forca]) %>
  <%= submit_tag("Pesquisar") %>
<% end %>

<table class="table table-sm">
<thead>
  <tr>
    <th scope="col">Id</th>
    <th scope="col">Nome</th>
    <th scope="col">Força</th>
    <th scope="col">Resistencia</th>
    <th scope="col">Agilidade</th>
    <th scope="col">Destreza</th>
    <th scope ="col"> Visualizar</th>
    <th scope ="col"> Editar</th>

  </tr>
  </thead>
  <% @personagem.each do |personagens| %>
<tbody>
    <tr>
      <th scope="row"> <%=personagens.id%></th>
      <td><%=personagens.nome %></td>
      <td><%=personagens.forca%></td>
      <td><%=personagens.resistencia%></td>
      <td><%=personagens.agilidade%></td>
      <td><%=personagens.destreza%></td>
      <td><%= link_to 'Visualizar', personagens, class: "btn btn-outline-primary"  %></td>
      <td><%= link_to 'Editar', edit_personagem_path(personagens), class: "btn btn-outline-success" %></td>

    </tr>
  </tbody>

  <% end %>

app/views/personagens/new.html.erb
<h1> Cadastro </h1>



<%= render 'form' %>

<%= link_to "Voltar", root_path %>

app/views/personagens/show.html.erb
<p id="Personagem"> </p>
<h3>Nome: <%= @personagem.nome %> </h2>
<ul>
<li>Forca: <%= @personagem.forca %> </li>
<li>Resistencia: <%= @personagem.resistencia %> </li>
<li>Agilidade: <%=@personagem.agilidade%></li>
<li>Destreza <%=@personagem.destreza%></li
</ul>


<h2>Poderes</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Tipo</th>
              <th colspan="5">Opções</th>
            </tr>
          </thead>

          <tbody>
            <% @personagem.poderes.each do |i| %>
              <tr>
                <td><%= i.nome %></td>
                <td><%= i.tipo %></td>
                <td><%= link_to 'Ver', i, class: "btn btn-success" %></td>
                <td><%= link_to 'Editar', edit_poder_path(i), class: "btn btn-warning" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>



<%= link_to 'Editar Perfil', edit_personagem_path(@personagem) %>
<%= link_to 'Inicio', root_path %>

app/views/poderes/edit.html.erb
<h1> Editar Poder </h1>

<%= form_for @poder do |f| %>
<p>
<%= f.label :nome %> <br />
<%= f.text_field :nome %>
</p>
<p>
<%= f.label :tipo %> <br />
<%= f.text_field :tipo %>
</p>

<p>
<%= f.submit "Editar",class:'btn btn-primary'%>
<%= link_to "Voltar",root_path, class:" btn btn-primary"%>
</p>
<% end %>

app/views/poderes/index.html.erb
<table class="table table-sm">
<thead>
  <tr>
    <th scope="col">Nome</th>
    <th scope="col">Tipo</th>

  </tr>
  </thead>
  <% @poder.each do |poder| %>
<tbody>
    <tr>

      <td><%=poder.nome %></td>
      <td><%=poder.tipo%></td>

      <td><%= link_to 'Visualizar', poder, class: "btn btn-outline-primary"  %></td>
      <td><%= link_to 'Editar', edit_poder_path(poder), class: "btn btn-outline-success" %></td>

    </tr>
  </tbody>
  <% end %>

app/views/poderes/new.html.erb
    <h1>Criar poder</h1>
    <%= form_for @poder do |f| %>

    <p>
        <%= f.label :personagem %> <br />
        <%= f.collection_select(:personagem_id, @personagens, :id, :nome, selected: params[:personagem_id])  %>
    </p>
    <p>
    <%= f.label :nome %> <br />
    <%= f.text_field :nome %>
    </p>
    <p>
    <%= f.label :tipo %> <br />
    <%= f.text_field :tipo %>
    </p>

    <p>
    <%= f.submit "Criar",class:'btn btn-primary'%>
    </p>
    <% end %>

app/views/poderes/show.html.erb
<p id="notice"><%= notice %> </p>
  <h2>Poder: <%= @poder.nome %> </h2>

   <h3>Tipo: <%= @poder.tipo %> </h3>

   <%= link_to 'Editar Poder', edit_poder_path ,class:"btn btn-warning"%>
    <%= link_to 'Personagem', @poder.personagem, class:"btn btn-info"%>





  </ul>